name = input("What is your name?\n")
age = input("How old are you?\n")
place = input("Where do you live?\n")
if name: print("Hello, " + name) 
else: print("You dont have a name?")
if age: print("Your age is " + age) 
else: print("Your age is so scary?")
if place: print("You live in " + place) 
else: print("You are from Earth?")